<h3><?php echo $this->translate('view.translation.index.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.index.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>
<p>
    <a class="button btn btn-primary" href="<?php echo $this->url('translation/management/settings'); ?>" title="<?php echo $this->translate('view.translation.management.gotoSettings'); ?>">
        <?php echo $this->translate('view.translation.management.gotoSettings'); ?>
    </a>

    <a class="button btn btn-primary" href="<?php echo $this->url('translation/management/import'); ?>" title="<?php echo $this->translate('view.translation.management.gotoImport'); ?>">
        <?php echo $this->translate('view.translation.management.gotoImport'); ?>
    </a>

    <a class="button btn btn-primary" href="<?php echo $this->url('translation/management/export'); ?>" title="<?php echo $this->translate('view.translation.management.gotoExport'); ?>">
        <?php echo $this->translate('view.translation.management.gotoExport'); ?>
    </a>

    <a class="button btn btn-primary" href="<?php echo $this->url('translation/management/build'); ?>" title="<?php echo $this->translate('view.translation.management.gotoBuild'); ?>">
        <?php echo $this->translate('view.translation.management.gotoBuild'); ?>
    </a>
</p>

<br />
<table class="table">
    <tr>
        <th>
            <?php echo $this->translate(['view.translation.entry.count', $this->entryCount]); ?>
        </th>
        <td>
            <a href="<?php echo $this->url('translation/entry'); ?>" title="<?php echo $this->translate('view.translation.entry.showAll'); ?>">
                <?php echo $this->translate('view.translation.entry.showAll'); ?>
            </a>
            <br />
            <a href="<?php echo $this->url('translation/entry/create'); ?>" title="<?php echo $this->translate('view.translation.entry.gotoCreate'); ?>">
                <?php echo $this->translate('view.translation.entry.gotoCreate'); ?>
            </a>
        </td>
    </tr>
    <tr>
        <th>
            <?php echo $this->translatePlural([['view.translation.language.countSingular', 'view.translation.language.countPlural'], $this->languageCount], $this->languageCount); ?>
        </th>
        <td>
            <a href="<?php echo $this->url('translation/language'); ?>" title="<?php echo $this->translate('view.translation.language.showAll'); ?>">
                <?php echo $this->translate('view.translation.language.showAll'); ?>
            </a>
            <br />
            <a href="<?php echo $this->url('translation/language/create'); ?>" title="<?php echo $this->translate('view.translation.language.gotoCreate'); ?>">
                <?php echo $this->translate('view.translation.language.gotoCreate'); ?>
            </a>
        </td>
    </tr>
    <tr>
        <th>
            <?php echo $this->translate(['view.translation.module.count', $this->moduleCount]); ?>
        </th>
        <td>
            <a href="<?php echo $this->url('translation/module'); ?>" title="<?php echo $this->translate('view.translation.module.showAll'); ?>">
                <?php echo $this->translate('view.translation.module.showAll'); ?>
            </a>
            <br />
            <a href="<?php echo $this->url('translation/module/create'); ?>" title="<?php echo $this->translate('view.translation.module.gotoCreate'); ?>">
                <?php echo $this->translate('view.translation.module.gotoCreate'); ?>
            </a>
        </td>
    </tr>
</table>