<h3><?php echo $this->translate('view.translation.language.create.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.language.create.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>
<?php
    $this->form->setAttribute('action', $this->url('translation/language/create'));
    echo $this->formDecorator($this->form);
?>
