<h3><?php echo $this->translate('view.translation.language.edit.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.language.edit.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('translation/language/edit', [
        'id' => $this->language->getId(),
    ]));
    echo $this->formDecorator($this->form);
    ?>
</div>