<h3><?php echo $this->translate('view.translation.entry.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.entry.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
<?php
    $this->form->setAttribute('action', $this->url('translation/entry'));
    echo $this->formDecorator($this->form);
?>
</div>

<div class="col-md-5">
    <a class="button btn btn-primary" href="<?php echo $this->url('translation/entry/create'); ?>" title="<?php echo $this->translate('view.translation.entry.gotoCreate'); ?>">
        <?php echo $this->translate('view.translation.entry.gotoCreate'); ?>
    </a>
</div>

<table id="translation-entries-list" class="table">
    <thead>
        <tr>
            <th>
                <?php echo $this->translate('view.translation.entry.string'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.translation.entry.module'); ?>
            </th>
            <th style="max-width: 20%; overflow: hidden;">
                <?php echo $this->translate('view.translation.entry.translations'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.actions'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->entries as $entry) : ?>
        <tr>
            <td class="word-break"><?php echo $entry->getString(); ?></td>
            <td><?php echo $entry->getModule()->getName(); ?></td>
            <td class="word-break small-img" style="max-width: 500px; overflow: hidden;">
                <?php foreach($entry->getTranslations() as $translation) :
                        $value = $translation->getTranslation();
                        if ($value === null) {
                            continue;
                        }
                ?>
                    <span class="translation-language text-primary">
                        <?php echo $translation->getLanguage()->getName(); ?>:
                    </span>
                    <br />
                    <span class="translation-translation">
                        <?php
                            if ($value === '') {
                                echo '&lt;leer&gt;';
                            }
                            else {
                                echo  $value;
                            }
                        ?>
                    </span><br />
                <?php endforeach; ?>
            </td>
            <td>
                <a href="<?php echo $this->url('translation/entry/edit', ['id' => $entry->getId()]); ?>" title="<?php echo $this->translate('view.translation.entry.gotoEdit'); ?>">
                    <?php echo $this->translate('view.translation.entry.gotoEdit'); ?>
                </a>
                <br />
                <a href="<?php echo $this->url('translation/entry/delete', ['id' => $entry->getId()]); ?>" title="<?php echo $this->translate('view.translation.entry.gotoDelete'); ?>">
                    <?php echo $this->translate('view.translation.entry.gotoDelete'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php if (!count($this->entries)) : ?>
        <tr>
            <td colspan="4" class="text-center">
                <?php echo $this->translate('message.translation.noEntriesFound'); ?>
            </td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>