<h3><?php echo $this->translate('view.translation.string.delete.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.string.delete.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('translation/string/delete', array(
        'id' => $this->string->getId(),
    )));
    echo $this->formDecorator($this->form);
    ?>
</div>