<h3>
    <?php
        echo $this->translate('view.translation.string.edit.heading');

        $this->headScript()
            ->appendFile($this->basePath().'/translation-module/translation-module.js')
?>
</h3>
<p>
    <?php echo $this->translate('view.translation.string.edit.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
<?php
    $this->form->setAttribute('action', $this->url('translation/string/edit', array(
        'id' => $this->string->getId(),
    )));
    echo $this->formDecorator($this->form);
?>
</div>