<h3><?php echo $this->translate('view.translation.string.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.string.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
<?php
    $this->form->setAttribute('action', $this->url('translation/string'));
    echo $this->formDecorator($this->form);
?>
</div>

<div class="col-md-5">
    <a class="button btn btn-primary" href="<?php echo $this->url('translation/string/create'); ?>" title="<?php echo $this->translate('view.translation.string.gotoCreate'); ?>">
        <?php echo $this->translate('view.translation.string.gotoCreate'); ?>
    </a>
</div>

<?php if (count($this->strings)) : ?>
<table id="translation-strings-list" class="table">
    <thead>
        <tr>
            <th>
                <?php echo $this->translate('view.translation.string.string'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.translation.string.module'); ?>
            </th>
            <th style="max-width: 20%; overflow: hidden;">
                <?php echo $this->translate('view.translation.string.translations'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.actions'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->strings as $string) : ?>
        <tr>
            <td class="word-break"><?php echo $string->getString(); ?></td>
            <td><?php echo $string->getModule()->getName(); ?></td>
            <td class="word-break small-img" style="max-width: 500px; overflow: hidden;">
                <?php foreach($string->getTranslations() as $translation) :
                        $value = $translation->getTranslation();
                        if ($value === null) {
                            continue;
                        }
                ?>
                    <span class="translation-language text-primary">
                        <?php echo $translation->getLanguage()->getName(); ?>:
                    </span>
                    <br />
                    <span class="translation-translation">
                        <?php
                            if ($value === '') {
                                echo '&lt;leer&gt;';
                            }
                            else {
                                echo  $value;
                            }
                        ?>
                    </span><br />
                <?php endforeach; ?>
            </td>
            <td>
                <a href="<?php echo $this->url('translation/string/edit', array('id' => $string->getId())); ?>" title="<?php echo $this->translate('view.translation.string.gotoEdit'); ?>">
                    <?php echo $this->translate('view.translation.string.gotoEdit'); ?>
                </a>
                <br />
                <a href="<?php echo $this->url('translation/string/delete', array('id' => $string->getId())); ?>" title="<?php echo $this->translate('view.translation.string.gotoDelete'); ?>">
                    <?php echo $this->translate('view.translation.string.gotoDelete'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<br />
<p>
    <?php echo $this->translate('message.translation.noStringsFound'); ?>
</p>
<?php endif; ?>