<h3><?php echo $this->translate('view.translation.management.import.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.management.import.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>
<?php
    $this->form->setAttribute('action', $this->url('translation/management/import'));
    echo $this->formDecorator($this->form);