<h3><?php echo $this->translate('view.translation.management.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.management.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<a class="button" href="<?php echo $this->url('translation/management/import'); ?>" title="<?php echo $this->translate('view.translation.management.gotoImport'); ?>">
    <?php echo $this->translate('view.translation.management.gotoImport'); ?>
</a><br />

<a class="button" href="<?php echo $this->url('translation/management/export'); ?>" title="<?php echo $this->translate('view.translation.management.gotoExport'); ?>">
    <?php echo $this->translate('view.translation.management.gotoExport'); ?>
</a><br />

<a class="button" href="<?php echo $this->url('translation/management/build'); ?>" title="<?php echo $this->translate('view.translation.management.gotoBuild'); ?>">
    <?php echo $this->translate('view.translation.management.gotoBuild'); ?>
</a><br />
