<h3><?php echo $this->translate('view.translation.module.delete.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.module.delete.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('translation/module/delete', [
        'id' => $this->module->getId(),
    ]));
    echo $this->formDecorator($this->form);
    ?>
</div>