<h3><?php echo $this->translate('view.translation.module.edit.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.translation.module.edit.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('translation/module/edit', array(
        'id' => $this->module->getId(),
    )));
    echo $this->formDecorator($this->form);
    ?>
</div>